#!/bin/bash
#  medieval – Modulo-Exemplo Da Instrucao EVAL
#
echo Recebi $# parametros.
i=1
while [ "$i" -le $# ]
do
    echo -n "parametro $i = "
    echo $`echo $i`     # Poderia ser echo \$$(echo $i)
    let i++
done
